config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'
  
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end
  

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 20}
    before_save :set_visits_count
    
    has_attached_file :cover, styles: { medium: "1280x720", thumb:"800x600"}
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
    
    def update_visits_count

        self.update(visits_count: self.visits_count + 1)
    end
    
    private 
    def set_visits_count
        self.visits_count ||= 0
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :articles
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index] 
    before_action :set_article, except: [:index, :new, :create]
    def index
        @articles = Article.all 
    end
    
    def show
       @article.update_visits_count
       @comment = Comment.new
    end
    
    def new
        @article = Article.new 
    end
    
    def edit
       
    end
    
    def create
        @article = current_user.articles.new(article_params)
        if @article.save
            redirect_to @article
        else
            render :new
        end
    end
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    def update

        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end
    
    private 

    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :body, :cover)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
    before_action :set_article
  before_action :authenticate_user!

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def set_article
    @article = Article.find(params[:article_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
    <%= form_for(@article) do |f| %>
        <% @article.errors.full_messages.each do |message| %>
            <div>
                *<%= message%>
            </div>
        <%end%>
        <%= f.text_field :title, placeholder: "Titulo"%>
        <%= f.text_area :body, placeholder: "Escriba su articulo aqui"%>
        <p>Portada: </p><%= f.file_field :cover%>
        <%= f.submit "Guardar", class:"btn waves-effect waves-light"%>
    <%end%>    

app/views/articles/edit.html.erb
<div class="col s12 m12 l12">
    <h1>Edite su articulo</h1>
    <%= render "form"%>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
 <div class="col s12 m12 l12">
    <h3><%= link_to article.title, article%></h3>
    <%= article.body%>
    <%= link_to "Eliminar", article, method: :delete, class:"btn waves-effect waves-light"%>
 </div>
<%end%>

app/views/articles/new.html.erb
<div class="col s12 m12 l12">
    <h1>Escriba su articulo</h1>
    <%= render "form"%>  
</div>

app/views/articles/show.html.erb
 <div class="col s12 m12 l12">
  <% unless @article.user.nil? %>
    <h3><%= @article.title%></h3>
    <%= image_tag @article.cover.url() %>
    <h5>escrito por: <%= @article.user.email %></h5>
  <%end%>
  <p>
   visitas: <%= @article.visits_count %>
  </p>
    <%= @article.body%>
     <%= link_to "Editar", edit_article_path(@article), class:"btn waves-effect waves-light"%>
 </div>
 <div>
  <h3>Comentarios:</h3>
  <div>
   <ul id="comments-box">
    <% @article.comments.each do |comment| %>
    <li>
     <%= comment.body %>
    </li>
    <li>
     <p>Escrito por: </p><%= comment.user.email %> 
    </li>
    <%end%>
   </ul>
  </div>
  <%= render "comments/form" %>
 </div>

app/views/comments/_form.html.erb
<!-- , remote: true, html: {id: "comments-form", :"data-type" => "json"} esto es para hacer el comentario de manera dinamica con ajax pero no recarga la pag -->
<%= form_for([@article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<%= render "partials/navegacion"%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container center-align">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/partials/_navegacion.html.erb
  <div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper #01579b light-blue darken-4">
          <a href="#!" class="brand-logo logo">Logo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li class="myli"><a href="sass.html">Sass</a></li>
            <li class="myli"><a href="badges.html">Components</a></li>
            <li class="myli"><a href="collapsible.html">Javascript</a></li>
            <li class="myli"><a href="mobile.html">Mobile</a></li>
            <% if user_signed_in? %>
              <li class="myli">
                <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
              </li>
            <%else%>
              <li class="myli">
                <%= link_to "Iniciar sesion", new_user_session_path%>
              </li class="myli">
              <li>
                <%= link_to "Crear Cuenta", new_user_registration_path%>
              </li class="myli">
            <%end%>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Mobile</a></li>
            <% if user_signed_in? %>
              <li>
                <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
              </li>
            <%else%>
              <li>
                <%= link_to "Iniciar sesion", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Crear Cuenta", new_user_registration_path%>
              </li>
            <%end%>
          </ul>
        </div>
    </nav>
  </div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido <%= current_user.email %></h1>
<%else%>
    <h1>Hola a todos</h1>
<%end%>